### ISSUE TITLE
[Arcs] Agitator and Mirror Plating

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#131]
[https://boardgamegeek.com/thread/3338448/article/44605009](https://boardgamegeek.com/thread/3338448/article/44605009)

Previous ruling indicated that Mirror Plating Intercept is not rolled so that it doesn't step on signal breakers. But then that implies it does not interact with agitator...

**Comment by jdyearsley** [comment]
This is a very funny one. So thematically, the intercept from Mirror Plating represents shots fired getting reflected, so it makes sense in how it interacts with Signal Breakers (which focuses on questions of stealth and surprise).

I think the most sensible thing to do is expand the Agitator's wording to all Intercept symbols, whether added or rolled, so the Mirror Plating triggers the Agitator's ability. Thematically this is slightly strange, but I'll take it over the alternative—otherwise it's unclear or does nothing. I'll add this errata.

**Comment by jdyearsley** [comment]
Added to file, production document, and branch!
