### ISSUE TITLE
[Arcs] Feast Day and Seat Removal

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#146]
we previously ruled:
Q:
>[ F16 09 Law](https://cards.ledergames.com/card/ARCS-F1609) provides removal of Seats when their city is "destroyed". What happens when the city is "replaced" by a free city (Song of Freedom), a starport (Living Structures), or a Rival city (Tyrant's Authority)?

A:
> Yes, this should apply to any situation where the city is "returned" to the player's supply

Is this consistent with the intention of [Feast Day](https://cards.ledergames.com/card/ARCS-F1613)?

and if Feast Day makes you a Lord. annexing with Tyrant's Authority should probably also make you a Lord?

**Comment by jdyearsley** [comment]
Good point. Realistically [F16 09 Law](https://cards.ledergames.com/card/ARCS-F1609) should read "removed" instead of "destroyed" to cover all such cases, since "destroy" is a distinct keyword. And yes, Feast Day / Tyrant's Authority should behave the same way.

Since this is errata, I'll put it in.

**Comment by jdyearsley** [comment]
Errata added to file, production document, and branch.

**Comment by jdyearsley** [comment]
Going to try automatically closing issues with one commit to branch.

**Comment by jdyearsley** [comment]
Didn't work, ha. Added to file, production document, and branch!
